app/__init__.py
from .app import app

app/app.py
from flask import Flask
from .routes import main_routes, eos_routes, tt1_routes, page_not_found, internal_server_error, Dampfturbine_routes
from flask_navigation import Navigation

app = Flask(__name__)
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'

nav = Navigation(app)
nav.Bar('top', [
    nav.Item('Home', 'main.home'),
    nav.Item('tt1', 'tt1.tt1'),
    nav.Item('Fluid/State', 'tt1.fluid_state'),
    nav.Item('EoS', 'eos.eos', items=[
        nav.Item('Equation of State', 'eos.eos'),
        nav.Item('T-S-Diagram', 'eos.ts'),
    ]),
    nav.Item('Dampfturbine', 'Dampfturbine.main'),
])

app.register_blueprint(main_routes)
app.register_blueprint(eos_routes)
app.register_blueprint(tt1_routes)
app.register_blueprint(Dampfturbine_routes)

app.register_error_handler(404, page_not_found)
app.register_error_handler(500, internal_server_error)

app/routes/_Dampfturbine.py
from flask import Blueprint, render_template, abort, request
import numpy as np
import json

Dampfturbine_routes = Blueprint('Dampfturbine', __name__, template_folder='templates')


@Dampfturbine_routes.route('/Dampfturbine')
def main():
    return render_template('Dampfturbine/main.html')

app/routes/__init__.py
from ._main import main_routes, page_not_found, internal_server_error
from ._eos import eos_routes
from ._tt1 import tt1_routes
from ._Dampfturbine import Dampfturbine_routes

app/routes/_eos.py
from flask import Blueprint, render_template, abort, request
import numpy as np
import json

eos_routes = Blueprint('eos', __name__, template_folder='templates')


@eos_routes.route('/eos')
def eos():
    return render_template('eos/eos.html')


@eos_routes.route('/eos/t-s', methods=['GET', 'POST'])
def ts():

    if request.method == 'POST':
        print(request.form.get('material'))
    return render_template('eos/ts.html', data=data)

@eos_routes.route('/eos/data')
def data():
    d = [{'x': x/10, 'y': np.sin(x/10)} for x in range(100)]
    return json.dumps(d)

app/routes/_main.py
from flask import Blueprint, render_template, flash

main_routes = Blueprint('main', __name__, template_folder='templates')


@main_routes.route('/')
def home():
    return render_template('main/home.html')

@main_routes.errorhandler(404)
def page_not_found(e):
    flash(e.description, 'danger')
    return render_template('main/404.html'), 404

@main_routes.errorhandler(500)
def internal_server_error(e):
    flash(e.description, 'danger')
    return render_template('main/500.html'), 500, 'hallo'

app/routes/_tt1.py
from flask import Blueprint, render_template, abort, request, Response
import numpy as np
import json
from tt.appendices.A1 import SaturatedWater
from tt.appendices.A3 import IdealGas
from tt.fluid_state import Fluid, Process, ThermoChart
import io
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


tt1_routes = Blueprint('tt1', __name__, template_folder='templates')


@tt1_routes.route('/tt1')
def tt1():
    return render_template('tt1/tt1.html')


@tt1_routes.route('/tt1/saturated_water')
def saturated_water():
    key = request.args.get('property', default=None, type=str)
    value = request.args.get('value', default=None, type=float)

    if value is None:
        try:
            value = request.args.get('value', default=None, type=str)
            value = [float(v) for v in json.loads(value)]
        except Exception as e:
            msg = f'value must be a number or an array of numbers -> given value: {value}'
            abort(500, msg)

    try:
        properties = SaturatedWater.get_state(key, value)
        return json.dumps(properties, ensure_ascii=False)
    except Exception as e:
        if key not in SaturatedWater.properties:
            prop_unit = [f'{p} in {u}' for p, u in SaturatedWater._prop_unit.items()]
            return f'property must be as string from {prop_unit}'
        elif value is None:

            return f'value must be a number or array of numbers'
        return f'no valid inputs -> {e}'

@tt1_routes.route('/fluid_state')
def fluid_state():
    return render_template('tt1/fluid_state.html')

@tt1_routes.route('/fluid_state_img')
def fluid_state_img():
    props = {'p': 100, 'v': 0.02}
    f1 = Fluid(fluid_name='Water', amount=1, properties=props)
    p12 = Process(f1, 'p', 'T', 400)

    f2 = p12.state_2
    p23 = Process(f2, 'T', 'p', 230)
    f3 = p23.state_2
    p34 = Process(f3, 'p', 'v', 0.002)
    f4 = p34.state_2
    p45 = Process(f4, 'T', 'v', 1)
    f5 = p45.state_2

    chrt = ThermoChart('pv', fluid=f1.fluid_name, x_property='h', x_unit='kJ/kg', y_property='p', y_unit='bar',
                       states=[f1, f2, f3, f4, f5], processes=[p12, p23, p34, p45], x_log=False, y_log=False)

    fig = chrt.create_empty()

    output = io.BytesIO()
    FigureCanvas(fig).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')


@tt1_routes.route('/tt1/ideal_gas')
def ideal_gas():
    key = request.args.get('property', default=None, type=str)
    value = request.args.get('value', default=None, type=float)

    if value is None:
        try:
            value = request.args.get('value', default=None, type=str)
            value = [float(v) for v in json.loads(value)]
        except Exception as e:
            msg = f'value must be a number or an array of numbers -> given value: {value}'
            abort(500, msg)

    try:
        properties = IdealGas.get_state(key, value)
        return json.dumps(properties, ensure_ascii=False)
    except Exception as e:
        if key not in IdealGas.properties:
            prop_unit = [f'{p} in {u}' for p, u in IdealGas._prop_unit.items()]
            return f'property must be as string from {prop_unit}'
        elif value is None:

            return f'value must be a number or array of numbers'
        return f'no valid inputs -> {e}'

app/templates/Dampfturbine/main.html
{% extends 'layout.html' %}

{% set T1 = 500 %}
{% set p1 = 2000000 %}
{% set p2 = 10000 %}
{% set x_Dampft = 0.95 %}

{% block content %}
    <h1>Dampfturbine</h1>
    Dampf wird in einer gut isolierten, stationär laufenden Turbine von Zustand 1 \(\left(p = 2~\mathrm{MPa}\right.\), \(\left.T = 500~\mathrm{°C}\right)\) auf Zustand 2
    \(\left(p = 10~\mathrm{kPa}\right.\), \(\left. x_{Dampf} = 0.95\right)\) entspannt. Die Änderungen in kinetischen und potentiellen Energien können vernachlässigt werden.

    <ol type="a">
        <!--- <ul style="list-style-type:lower-latin"> --->
        <li>Bestimmen Sie die spezifische Turbinenarbeit, \(\frac{\dot{W}_{CV}}{\dot{m}}\), in \(\mathrm{kJ/kg}\) und die spezifische Entropieproduktionsrate, \(\frac{\dot{\sigma}_{CV}}{\dot{m}}\), in \(\mathrm{kJ/(kg\,K)}\).</li>
        <li>Ist der beschreibene Prozess möglich? Erklären Sie Ihre Antwort.</li>
        <li>Zeichnen Sie den Prozess in einem T-s Diagramm</li>
        <li>Bestimmen Sie die spezifische Turbinenarbeit in \(\mathrm{kJ/kg}\), für den Fall, dass die Turbine den Dampf <em>reversibel</em> auf den gleichen Enddruck entspannt.</li>
        <li>Bestimmen Sie den isentropen Wirkungsgrad der Turbine, din in Teil a berechnet wurde.</li>
        <!--- </ul> --->
    </ol>

    <h2>Lösung</h2>
    <h5>Teilaufgabe a</h5>
    bekannt ist
    <ul>
        <li>Zustand 1: \(T = 500~\mathrm{°C}\), \(p = 2~\mathrm{MPa} = 2e6~\mathrm{Pa}\)</li>
        <li>Zustand 2: \(p = 10~\mathrm{kPa} = 1e4~\mathrm{Pa}\), \(x_{Dampf} = 0.95\)</li>
    </ul>
    daraus folgt
    <ul>
        <li>Zustand 1: überhitzter Wasserdampf &rarr; Tabelle A-3</li>
        <li>Zustand 2: Nassdampfgebiet &rarr; Tabelle A-1</li>
    </ul>
    <b>Enthalpie und Entropie</b> für Zustände bestimmen, <br>
    wobei zu überprüfen, ob Zustand in Tabelle oder ob interpoliert werden muss
    <ul>
        <li>Zustand 1</li>
        <ol type="i">
            <li>in Tabelle<br>
                \(h_1 = 3467.6~\mathrm{kJ/kg}\), \(s_1 = 7.4317~\mathrm{kJ/kg\,K}\)
            </li>
            <li>nicht in Tabelle<br>
                ...
            </li>

        </ol>
        <li>Zustand 2</li>
        <ol type="i">
            <li>in Tabelle<br>
                \(h_{2,g} = 2584.7~\mathrm{kJ/kg}\), \(h_{2,f} = 191.83~\mathrm{kJ/kg}\), <br>
                \(s_{2,g} = 7.77516~\mathrm{kJ/kg\,K}\), \(s_{2,f} = 7.4317~\mathrm{kJ/kg\,K}\)
            </li>
            <li>nicht in Tabelle<br>
                ...
            </li>
            <li>"Nassdampfbereich" berechnen</li>
                \(h_2 = h_{2,f} + x \left(h_{2,g}-h_{2,f}\right)\) <br>
                \( \begin{align}
                    h_2 & = h_{2,f} + x \left(h_{2,g}-h_{2,f}\right) \\
                        & = 191.83~\mathrm{kJ/kg} + 0.95 \, (2584.7-191.83)~\mathrm{kJ/kg} \\
                        & = 2465.06~\mathrm{kJ/kg}
                \end{align} \)
        </ol>
    </ul>

    <b>Massenbilanz</b> <br>
    \( \frac{d\,m_{CV}}{dt} = \dot{m}_1 - \dot{m}_2 \) <br>
    ?Annahme gleiche Massenströme?: <br>
    \(\begin{align}
        & \Rightarrow & \frac{d\,m_{CV}}{dt} & = 0 \\
        & \Leftrightarrow & \frac{d\,m_{CV}}{dt} & = \dot{m}_1 - \dot{m}_2 = 0 \\
        & \Leftrightarrow & \dot{m}_1 & = \dot{m}_2 = \dot{m}
    \end{align} \)
    <br> <br>

    <b>Energiebilanz</b> <br>
    \( \frac{d\,E_{CV}}{dt} = \Delta{KE} + \Delta{PE} + \dot{m}_1 h_1 - \dot{m}_2 h_2 + \dot{W}_{CV} + \dot{Q}_{CV} \)
    <ul>
        <li>kinetische und potentielle Energien vernachlässigbar: \(\Delta{KE} = \Delta{PE} = 0\)</li>
        <li>stationär: \(\frac{d\,E_{CV}}{dt} = 0\)</li>
        <li>gut isoliert, adiabat: \(\dot{Q}_{CV} = 0\)</li>
    </ul>
    es folgt <br>
    \( \begin{align}
    & \Rightarrow & \frac{d\,E_{CV}}{dt} & = 0 = \dot{m}_1 h_1 - \dot{m}_2 h_2 + \dot{W}_{CV} \\
    & \Leftrightarrow & \dot{W}_{CV} & = \dot{m}_2 h_2 - \dot{m}_1 h_1
    \end{align} \)
    <br>
    mit Massenbilanz <br>
    \( \begin{align}
    & \Rightarrow & \dot{W}_{CV} & = \dot{m} (h_2 - h_1) \\
    & \Leftrightarrow & \frac{\dot{W}_{CV}}{\dot{m}} & = h_2 - h_1 = 2465.06~\mathrm{kJ/kg} - 3467.6~\mathrm{kJ/kg} = -1002.5~\mathrm{kJ/kg}
    \end{align} \)
    <br> <br>

    <b>Entropiebilanz</b> <br>
    \( \frac{d\,S_{CV}}{dt} = \dot{m}_1 s_1 - \dot{m}_2 s_2 + \frac{\dot{Q}_{CV}}{T} + \dot{\sigma}_{CV} \)
    <ul>
        <li>stationär: \(\frac{d\,S_{CV}}{dt} = 0\)</li>
        <li>gut isoliert, adiabat: \(\dot{Q}_{CV} = 0\)</li>
    </ul>
    daraus folgt <br>
    \( \begin{align}
    & \Rightarrow & \frac{d\,S_{CV}}{dt} & = \dot{m} \left(s_1 - s_2\right) + \dot{\sigma}_{CV} = 0 \\
    & \Leftrightarrow & \frac{\dot{\sigma}_{CV}}{\dot{m}} & = s_2 - s_1 = 7.7752~\mathrm{kJ/kg\,K} - 7.4317~\mathrm{kJ/kg\,K} = 0.3435~\mathrm{kJ/kg\,K}
    \end{align} \)
    <br> <br>

    <h5>Teilaufgabe b</h5>
    Prozess ist nur möglich, wenn die spezifische Entropieproduktionsrate \( \frac{\dot{\sigma}_{CV}}{\dot{m}} \) grösser als 0 ist <br>
    von Teilaufgabe a): \( \frac{\dot{\sigma}_{CV}}{\dot{m}} = 0.3435~\mathrm{kJ/kg\,K} \) und somit grösser als 0 <br>
    \(\Rightarrow\) Prozess ist möglich, da \(\dot{m} \neq 0 \) und somit \(\dot{\sigma}_{CV} > 0 \)
    <br> <br>

    <h5>Teilaufgabe c</h5>
    Diagramm ....
    <br> <br>

    <h5>Teilaufgabe d</h5>
    Bei einem reversiblen Prozess  ist \(\dot{\sigma}_{CV} = 0\), <br>
    daraus folgt somit, dass \(s_{2,s} = s_1\) ist <br>
    der Zustand ist weiterhin im Zweiphasengebiet (warum???), somit kann über das Hebelgesetz, der Dampfanteil berechnet werden <br>
    \( x_{2,s} = \frac{s_{2,s}-s_{1,f}}{s_{1,g}-s_{1,f}} = \frac{(7.4317-0.6493)~\mathrm{kJ/kg\,K}}{(8.1502-0.6493)~\mathrm{kJ/kg\,K}} = 0.9042 \) <br>
    damit kann nun die Enthalpie berechnet werden <br>
    \( h_{2,s} = h_{2,f} + x_{2,s} \left(h_{2,g} - h_{2,f}\right) = ... = 2355.4~\mathrm{kJ/kg} \) <br>
    daraus folgt für die spezifische Turbinenarbeit <br>
    \( \frac{\dot{W}_{CV}}{\dot{m}} = h_{2,s} - h_1 = ... = 1112.62~\mathrm{kJ/kg} \)
    <br> <br>

    <h5>Teilaufgabe e</h5>
    \(\eta_{isen} = \frac{\left(\frac{\dot{W}_{CV}}{\dot{m}}\right)_{real} }{ \left(\frac{\dot{W}_{CV}}{\dot{m}}\right)_{ideal}} = \frac{\Delta\,h_{real}}{\Delta\,h_{ideal}} = \frac{1002.5~\mathrm{kJ/kg}}{1112.6~\mathrm{kJ/kg}} = 0.9014\)


{% endblock %}

app/templates/eos/eos.html
{% extends 'layout.html' %}

{% block content %}
<h1>Equation of state</h1>
Content
{% endblock %}

app/templates/eos/ts.html
{% extends 'layout.html' %}

{% block content %}
<h1>T-S</h1>

{% set materials = ['H20', 'RJ45'] %}

<form action="{{ url_for('eos.ts') }}" method="post">
    <div class="form-group row">
        <label for="material" class="col-sm-3 col-form-label">Material</label>
        <div class="col-sm-9">
            <select class="custom-select" id="material" name="material">
                {% for mat in materials %}
                <option value="{{ mat }}">{{ mat }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label for="colFormLabel" class="col-sm-3 col-form-label">Some Info</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="colFormLabel" placeholder="placeholder-text">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-3">Checkbox</div>
        <div class="col-sm-9">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                    Example checkbox
                </label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
</form>
<hr>
<canvas id="t-s-chart" width="400" height="400"></canvas>




<script src="{{ url_for('static', filename='scripts/t_s_chart.js') }}"></script>

{% endblock %}

app/templates/footer.html
<!-- Footer -->

<footer class="page-footer font-small text-light bg-dark pt-4 mt-3 d-none">

    <!-- Footer Elements -->
    <div class="container">
        <!--Grid row-->
        <div class="row">
            <div class="col-md-6">
                <h6>Created by:</h6>
                <ul>
                    <li>Institut für Biomasse und Ressourceneffizient</li>
                    <li>Timothy Griffin </li>
                    <li>Stefan Roth</li>
                    <li>Tobias Schmocker</li>
                    <li>Fabienne Mangold</li>
                    <li>Paul Raper</li>
                </ul>
            </div>
            <div class="col-md-6">
                <h6>External Links</h6>
                <ul>
                    <li>
                        <a href="https://www.fhnw.ch/de/die-fhnw/hochschulen/ht/institute/institut-fuer-biomasse-und-ressourceneffizienz">
                            Institut für Biomasse und Ressourceneffizienz</a></li>
                    <li><a href="https://www.fhnw.ch/de/studium/technik/energie-umwelttechnik">
                        Energie- und Umwelttechnik</a></li>
                </ul>
            </div>
        </div>
        <!--Grid row-->
    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="https://www.fhnw.ch"> Fachhochschule Nordwestschweiz</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

<script>
    $(function () {
        let f = $('footer');
        f.removeClass('d-none');
        if ($(document.body).height() < ($(window).height() - f.height())) {
            f.attr('style', 'position: fixed!important; bottom: 0px; width: 100%;');
        } else {
            f.attr('style', 'position: relative');
        }
    });
</script>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1>

    <title>Thermodynamics@FHNW</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>

    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js"></script>-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

</head>
<body>
<header>
    {% include 'nav_bar.html' %}
</header>
<div class="container p-3">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
</body>
</html>

app/templates/main/home.html
{% extends 'layout.html' %}

{% block content %}
<h1>Thermodynamics by FHNW</h1>
Die Grundlagen der Thermodynamik liefern die Basis zur quantitativen Beurteilung und Optimierung von energetischen
Prozessen. Dafür werden in diesem Modul nützliche Bilanzgleichungen erstellt, charakterisierende Begriffe definiert
(Wirkungsgrad, Entropie) und die Eigenschaften von wichtigen Stoffen beschrieben (Luft, Wasser, Kältemittel). Diese
Grundlagen werden von den Teilnehmern in vielen praktischen Rechenaufgaben angewendet.

{% endblock %}

app/templates/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='img/logos/FHNW.png') }}" height="30px"
             class="d-inline-block align-center mr-3" alt="">
        Thermodynamics</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% for nav_item in nav.top %}
            {% if nav_item.items %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {{ 'active' if nav_item.is_active else '' }}"
                   href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    {{ nav_item.label }}{% if nav_item.is_active %}
                    <span class="sr-only">(current)</span>{% endif %}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for nav_sub_item in nav_item.items %}
                    <li class="dropdown-item {{ 'active' if nav_sub_item.is_active else '' }}">
                        <a class="nav-link{{ ' active' if nav_sub_item.is_active else '' }}"
                           href="{{ nav_sub_item.url }}">
                            {{ nav_sub_item.label }}{% if nav_sub_item.is_current %}
                            <span class="sr-only">(current)</span>{% endif %}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link{{ ' active' if nav_item.is_active else '' }}"
                   href="{{ nav_item.url }}">
                    {{ nav_item.label }}{% if nav_item.is_current %}
                    <span class="sr-only">(current)</span>{% endif %}
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>

</nav>

app/templates/tt1/fluid_state.html
{% extends 'layout.html' %}

{% block content %}
<h1>Fluid State</h1>
<img src="{{url_for('tt1.fluid_state_img') }}">
{% endblock %}

app/templates/tt1/tt1.html
{% extends 'layout.html' %}

{% block content %}
<h1>Technische Thermodynamik 1</h1>
<p>Die Grundlagen der Thermodynamik liefern die Basis zur quantitativen Beurteilung und Optimierung von energetischen
    Prozessen. Dafür werden in diesem Modul nützliche Bilanzgleichungen erstellt, charakterisierende Begriffe definiert
    (Wirkungsgrad, Entropie) und die Eigenschaften von wichtigen Stoffen beschrieben (Luft, Wasser, Kältemittel). Diese
    Grundlagen werden von den Teilnehmern in vielen praktischen Rechenaufgaben angewendet.</p>
<hr>
<h3>Check out the API for saturated water</h3>
<p>Get all properties of saturated water using a URL with a corresponding input property:</p>
<p><a href="{{ url_for('tt1.saturated_water', property='T', value=50) }}">Temperature: T=50 °C</a><br>
<a href="{{ url_for('tt1.saturated_water', property='P', value=2.7) }}">Pressure: P=2.7 bar</a><br>
<a href="{{ url_for('tt1.saturated_water', property='hf', value=546) }}">Enthalpy of fluid: hf=546 kJ/kg</a></p>
<p>It is also possible to get multiple states with one request using an array as input value:</p>
<p><a href="{{ url_for('tt1.saturated_water', property='P', value='[2.7, 2.8, 2.9]') }}">Pressures: P=[2.7, 2.8, 2.9] bar</a></p>
<p>You can use the API also in MATLAB:</p>
<code>
    >> data = webread('<script>document.write(document.URL)</script>saturated_water/?property=hf&value=[546,547]')<br>
    >> data = jsondecode(data)<br>
    >> data = struct2table(data)<br>
</code>
<hr>
<h3>Learning Videos</h3>
<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/kcNhwaVFk5s" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
{% endblock %}